begin;

create table if not exists public.reenvios_protocolos_medicos (
  id bigint generated by default as identity primary key,
  modalidade text not null check (modalidade in ('substituicao', 'troca')),
  solicitacao_id bigint not null,
  protocolo text not null,
  requisitante_matricula text not null,
  destinatarios text[] not null check (cardinality(destinatarios) between 1 and 2),
  status text not null default 'processando' check (status in ('processando', 'enviado', 'falhou')),
  erro text,
  criado_em timestamptz not null default now(),
  concluido_em timestamptz
);

create index if not exists reenvios_protocolos_medicos_solicitacao_idx
  on public.reenvios_protocolos_medicos (modalidade, solicitacao_id, criado_em desc);

create or replace function public.validar_limite_reenvio_protocolo_medico()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  ultimo_envio timestamptz;
  total_24h integer;
begin
  perform pg_advisory_xact_lock(
    hashtextextended(new.modalidade || ':' || new.solicitacao_id::text, 0)
  );

  select max(criado_em), count(*)::integer
    into ultimo_envio, total_24h
  from public.reenvios_protocolos_medicos
  where modalidade = new.modalidade
    and solicitacao_id = new.solicitacao_id
    and criado_em >= current_timestamp - interval '24 hours'
    and (
      status = 'enviado'
      or (status = 'processando' and criado_em >= current_timestamp - interval '10 minutes')
    );

  if total_24h >= 3 then
    raise exception 'Limite de 3 reenvios em 24 horas atingido.' using errcode = 'P0001';
  end if;

  if ultimo_envio is not null and ultimo_envio > current_timestamp - interval '2 minutes' then
    raise exception 'Aguarde 2 minutos antes de reenviar novamente.' using errcode = 'P0001';
  end if;

  return new;
end;
$$;

drop trigger if exists validar_limite_reenvio_protocolo_medico_trigger
  on public.reenvios_protocolos_medicos;
create trigger validar_limite_reenvio_protocolo_medico_trigger
before insert on public.reenvios_protocolos_medicos
for each row execute function public.validar_limite_reenvio_protocolo_medico();

alter table public.reenvios_protocolos_medicos enable row level security;
alter table public.reenvios_protocolos_medicos force row level security;
revoke all on table public.reenvios_protocolos_medicos from anon, authenticated;
revoke all on sequence public.reenvios_protocolos_medicos_id_seq from anon, authenticated;

commit;
