-- Área Médica: execute somente se estas tabelas ainda não existirem.
-- Sem acesso direto do navegador: todas as operações passam pelas APIs do servidor.
begin;

create table public.substituicoes_medicas_contadores (
  competencia char(4) primary key check (competencia ~ '^[0-9]{4}$'),
  ultimo integer not null check (ultimo > 0)
);

create table public.trocas_plantao_medicas_contadores (
  competencia char(4) primary key check (competencia ~ '^[0-9]{4}$'),
  ultimo integer not null check (ultimo > 0)
);

create table public.substituicoes_medicas (
  id bigint generated by default as identity primary key,
  protocolo text not null unique,
  solicitante_id bigint not null,
  cpf_solicitante char(11) not null check (cpf_solicitante ~ '^[0-9]{11}$'),
  matricula_solicitante text not null,
  nome_solicitante text not null,
  funcao_solicitante text not null,
  email_solicitante text not null check (
    email_solicitante = lower(email_solicitante)
    and email_solicitante ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]{2,}$'
  ),
  data_plantao date not null,
  tipo_plantao text not null check (tipo_plantao in ('SD', 'SN', '24H', 'ROTINA', 'AMBULATÓRIO')),
  substituto_id bigint not null,
  cpf_substituto char(11) not null check (cpf_substituto ~ '^[0-9]{11}$'),
  matricula_substituto text not null,
  nome_substituto text not null,
  funcao_substituto text not null,
  status text not null default 'recebido' check (status in ('recebido', 'cancelado')),
  termos_versao text not null,
  termos_aceitos_em timestamptz not null default now(),
  criado_em timestamptz not null default now(),
  cancelado_em timestamptz,
  constraint substituicao_ids_distintos check (solicitante_id <> substituto_id),
  constraint substituicao_cpfs_distintos check (cpf_solicitante <> cpf_substituto),
  constraint substituicao_cancelamento_coerente check (
    (status = 'recebido' and cancelado_em is null)
    or (status = 'cancelado' and cancelado_em is not null)
  )
);

create unique index substituicoes_medicas_plantao_ativo_idx
  on public.substituicoes_medicas (solicitante_id, data_plantao, tipo_plantao)
  where status = 'recebido';
create index substituicoes_medicas_solicitante_idx
  on public.substituicoes_medicas (solicitante_id, criado_em desc);

create table public.trocas_plantao_medicas (
  id bigint generated by default as identity primary key,
  protocolo text not null unique,
  solicitante_id bigint not null,
  cpf_solicitante char(11) not null check (cpf_solicitante ~ '^[0-9]{11}$'),
  matricula_solicitante text not null,
  nome_solicitante text not null,
  funcao_solicitante text not null,
  email_solicitante text not null check (
    email_solicitante = lower(email_solicitante)
    and email_solicitante ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]{2,}$'
  ),
  data_plantao_solicitante date not null,
  tipo_plantao_solicitante text not null check (tipo_plantao_solicitante in ('SD', 'SN', '24H', 'ROTINA', 'AMBULATÓRIO')),
  solicitado_id bigint not null,
  cpf_solicitado char(11) not null check (cpf_solicitado ~ '^[0-9]{11}$'),
  matricula_solicitado text not null,
  nome_solicitado text not null,
  funcao_solicitado text not null,
  data_plantao_solicitado date not null,
  tipo_plantao_solicitado text not null check (tipo_plantao_solicitado in ('SD', 'SN', '24H', 'ROTINA', 'AMBULATÓRIO')),
  chave_troca text not null,
  status text not null default 'recebido' check (status in ('recebido', 'cancelado')),
  termos_versao text not null,
  termos_aceitos_em timestamptz not null default now(),
  criado_em timestamptz not null default now(),
  cancelado_em timestamptz,
  constraint troca_ids_distintos check (solicitante_id <> solicitado_id),
  constraint troca_cpfs_distintos check (cpf_solicitante <> cpf_solicitado),
  constraint troca_plantoes_distintos check (
    data_plantao_solicitante <> data_plantao_solicitado
    or tipo_plantao_solicitante <> tipo_plantao_solicitado
  ),
  constraint troca_cancelamento_coerente check (
    (status = 'recebido' and cancelado_em is null)
    or (status = 'cancelado' and cancelado_em is not null)
  )
);

create unique index trocas_medicas_chave_ativa_idx
  on public.trocas_plantao_medicas (chave_troca)
  where status = 'recebido';
create index trocas_medicas_solicitante_idx
  on public.trocas_plantao_medicas (solicitante_id, criado_em desc);
create index trocas_medicas_solicitado_idx
  on public.trocas_plantao_medicas (solicitado_id, criado_em desc);

create function public.preparar_substituicao_medica()
returns trigger language plpgsql security definer
set search_path = pg_catalog, public
as $$
declare
  competencia_atual text;
  proximo integer;
begin
  competencia_atual := to_char(current_timestamp at time zone 'America/Sao_Paulo', 'MMYY');
  if to_char(new.data_plantao, 'MMYY') <> competencia_atual then
    raise exception 'A substituição deve pertencer ao mês vigente.' using errcode = '22023';
  end if;
  if (upper(new.funcao_solicitante) not like '%MEDICO%' and upper(new.funcao_solicitante) not like '%MÉDICO%')
     or (upper(new.funcao_substituto) not like '%MEDICO%' and upper(new.funcao_substituto) not like '%MÉDICO%') then
    raise exception 'A substituição somente pode ocorrer entre funções médicas.' using errcode = '22023';
  end if;
  insert into public.substituicoes_medicas_contadores (competencia, ultimo)
  values (competencia_atual, 1)
  on conflict (competencia) do update
    set ultimo = public.substituicoes_medicas_contadores.ultimo + 1
  returning ultimo into proximo;
  new.protocolo := 'HMRG/SUB' || competencia_atual || '-' || lpad(proximo::text, 4, '0');
  new.email_solicitante := lower(trim(new.email_solicitante));
  new.status := 'recebido';
  new.cancelado_em := null;
  return new;
end;
$$;

create function public.preparar_troca_plantao_medica()
returns trigger language plpgsql security definer
set search_path = pg_catalog, public
as $$
declare
  competencia_atual text;
  proximo integer;
  lado_a text;
  lado_b text;
begin
  competencia_atual := to_char(current_timestamp at time zone 'America/Sao_Paulo', 'MMYY');
  if to_char(new.data_plantao_solicitante, 'MMYY') <> competencia_atual
     or to_char(new.data_plantao_solicitado, 'MMYY') <> competencia_atual then
    raise exception 'Os dois plantões devem pertencer ao mês vigente.' using errcode = '22023';
  end if;
  if (upper(new.funcao_solicitante) not like '%MEDICO%' and upper(new.funcao_solicitante) not like '%MÉDICO%')
     or (upper(new.funcao_solicitado) not like '%MEDICO%' and upper(new.funcao_solicitado) not like '%MÉDICO%') then
    raise exception 'A troca somente pode ocorrer entre funções médicas.' using errcode = '22023';
  end if;
  lado_a := new.solicitante_id::text || '|' || new.data_plantao_solicitante::text || '|' || new.tipo_plantao_solicitante;
  lado_b := new.solicitado_id::text || '|' || new.data_plantao_solicitado::text || '|' || new.tipo_plantao_solicitado;
  new.chave_troca := least(lado_a, lado_b) || '<>' || greatest(lado_a, lado_b);
  insert into public.trocas_plantao_medicas_contadores (competencia, ultimo)
  values (competencia_atual, 1)
  on conflict (competencia) do update
    set ultimo = public.trocas_plantao_medicas_contadores.ultimo + 1
  returning ultimo into proximo;
  -- TPM = Troca de Plantão Médica; depois vem MMAA.
  new.protocolo := 'HMRG/TPM' || competencia_atual || '-' || lpad(proximo::text, 4, '0');
  new.email_solicitante := lower(trim(new.email_solicitante));
  new.status := 'recebido';
  new.cancelado_em := null;
  return new;
end;
$$;

create trigger preparar_substituicao_medica_trigger
before insert on public.substituicoes_medicas
for each row execute function public.preparar_substituicao_medica();
create trigger preparar_troca_plantao_medica_trigger
before insert on public.trocas_plantao_medicas
for each row execute function public.preparar_troca_plantao_medica();

create function public.validar_cancelamento_substituicao_medica()
returns trigger language plpgsql security definer
set search_path = pg_catalog, public
as $$
declare hoje date := (current_timestamp at time zone 'America/Sao_Paulo')::date;
begin
  if old.status = 'cancelado' or new.status <> 'cancelado' then
    raise exception 'A única alteração permitida é cancelar um registro ativo.' using errcode = '22023';
  end if;
  if hoje >= old.data_plantao then
    raise exception 'O prazo para cancelamento foi encerrado.' using errcode = '22023';
  end if;
  new := old;
  new.status := 'cancelado';
  new.cancelado_em := current_timestamp;
  return new;
end;
$$;

create function public.validar_cancelamento_troca_medica()
returns trigger language plpgsql security definer
set search_path = pg_catalog, public
as $$
declare
  hoje date := (current_timestamp at time zone 'America/Sao_Paulo')::date;
  primeiro_plantao date := least(old.data_plantao_solicitante, old.data_plantao_solicitado);
begin
  if old.status = 'cancelado' or new.status <> 'cancelado' then
    raise exception 'A única alteração permitida é cancelar um registro ativo.' using errcode = '22023';
  end if;
  if hoje >= primeiro_plantao then
    raise exception 'O prazo para cancelamento foi encerrado.' using errcode = '22023';
  end if;
  new := old;
  new.status := 'cancelado';
  new.cancelado_em := current_timestamp;
  return new;
end;
$$;

create trigger validar_cancelamento_substituicao_medica_trigger
before update on public.substituicoes_medicas
for each row execute function public.validar_cancelamento_substituicao_medica();
create trigger validar_cancelamento_troca_medica_trigger
before update on public.trocas_plantao_medicas
for each row execute function public.validar_cancelamento_troca_medica();

alter table public.substituicoes_medicas enable row level security;
alter table public.substituicoes_medicas force row level security;
alter table public.trocas_plantao_medicas enable row level security;
alter table public.trocas_plantao_medicas force row level security;
alter table public.substituicoes_medicas_contadores enable row level security;
alter table public.substituicoes_medicas_contadores force row level security;
alter table public.trocas_plantao_medicas_contadores enable row level security;
alter table public.trocas_plantao_medicas_contadores force row level security;

revoke all on table public.substituicoes_medicas from anon, authenticated;
revoke all on table public.trocas_plantao_medicas from anon, authenticated;
revoke all on table public.substituicoes_medicas_contadores from anon, authenticated;
revoke all on table public.trocas_plantao_medicas_contadores from anon, authenticated;
revoke all on sequence public.substituicoes_medicas_id_seq from anon, authenticated;
revoke all on sequence public.trocas_plantao_medicas_id_seq from anon, authenticated;
revoke all on function public.preparar_substituicao_medica() from public, anon, authenticated;
revoke all on function public.preparar_troca_plantao_medica() from public, anon, authenticated;
revoke all on function public.validar_cancelamento_substituicao_medica() from public, anon, authenticated;
revoke all on function public.validar_cancelamento_troca_medica() from public, anon, authenticated;

commit;
